#!/bin/bash

# Update and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<'EOF'
frontend web-frontend
    bind *:80
    mode http
    default_backend web-servers

backend web-servers
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
