#!/bin/bash

# Update and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a basic HTML file
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Configure custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Configure Nginx with custom header
sudo sed -i '/server_name _;/a \\n\tadd_header X-Served-By "$HOSTNAME";' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
